apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort
  selector:
    app: flask-app
  ports:
    - port: 5000          # Port the service will expose
      targetPort: 5000    # Port the container listens on
      nodePort: 30007     # External port on the Node (must be between 30000–32767)
